project:
  type: website
  output-dir: docs

website:
  title: "Karla Buitrago-Yepes' ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio_ab_aggregations.qmd
        text: "Portfolio"
    right: 
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/karla-buitrago-yepes-5a278a28b/
    - icon: github
      text: Github
      href: https://github.com/Karlabuye

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    linkcolor:  red

editor: visual

